### ISSUE TITLE
PR#53 broke Windows builds

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/project-athena#103]
Configuring a Windows build with an empty build directory fails:
```
D:\Workspaces\CtrlAltStudio\Athena-C\Athena-C\build>cmake .. -G "Visual Studio 16 2019" -A x64
-- EXTERNAL_BUILD_ASSETS: https://athena-public.s3.amazonaws.com
Traceback (most recent call last):
  File "D:/Workspaces/CtrlAltStudio/Athena-C/Athena-C/prebuild.py", line 22, in <module>
    import hifi_vcpkg
  File "D:\Workspaces\CtrlAltStudio\Athena-C\Athena-C\hifi_vcpkg.py", line 12, in <module>
    import distro
ModuleNotFoundError: No module named 'distro'
CMake Error at CMakeLists.txt:81 (message):
  vcpkg configuration missing.
```

Empty build directory
cmake on kasen/core just immediately prior to PR#53 succeeds.

Empty build directory
cmake on Kasen/core at PR#53 fails. <<< bad

Empty build directory
cmake on kasen/core just immediately prior to PR#53 succeeds.
Update to latest kasen/core without cleaning build directory.
cmake on kasen/core succeeds. <<< manual work-around

https://github.com/kasenvr/project-athena/pull/53 "Add support for Ubuntu 19.10, modernize vcpkg"

**Comment by daleglass** [comment]
It requires the 'distro' Python3 package. You should be able to install it with pip3.

This change was made because the previously used platform.linux_distribution() is deprecated, see at the bottom of https://docs.python.org/2/library/platform.html

> This function is deprecated since Python 3.5 and removed in Python 3.8. See alternative like the distro package.

**Comment by ctrlaltdavid** [comment]
I see that BUILD_WIN.md was subsequently updated with this extra build environment setup step.
