### ISSUE TITLE
Allowing serverless Json work on http:

### ISSUE THREAD

**Issue by Novajone** [kasenvr/project-athena#106]
I tested this out I transfer the serverless domain contents into a  Dropbox and it provided me with the links to go there so I put the links into the goto section of hifi client and wouldn’t teleport me there directly.

**Comment by ctrlaltdavid** [comment]
PR: https://github.com/kasenvr/project-athena/pull/108

**Comment by ctrlaltdavid** [comment]
PR: https://github.com/kasenvr/project-athena/pull/160

**Comment by ctrlaltdavid** [comment]
Merged.
