### ISSUE TITLE
Have the "View > Selfies" working in VR.

### ISSUE THREAD

**Issue by KebHelion** [kasenvr/project-athena#110]
Not a high priority, but:

Could we have the "View > Selfies" working in VR.
or fix the original doppelganger mirror application
(the easiest fix would do)

**Comment by KebHelion** [comment]
Alezia Kurdis just released a fixed version of the doppelganger-mirror application.
If some one can add it to "scripts/communityModules" or "scripts/modules" folder, then I guess we could simply close this issue.

Here's the application:
[doppelganger-mirror.zip](https://github.com/kasenvr/project-athena/files/4171351/doppelganger-mirror.zip)

**Comment by AleziaKurdis** [comment]
I suggest we close that one.

**Comment by KebHelion** [comment]
Closing it.
