### ISSUE TITLE
Bug: scripts fail to load

### ISSUE THREAD

**Issue by SilverfishVR** [kasenvr/project-athena#122]
This one was invented for 0.86.0 I think (or was it 85? I reported the bug on oct. 4th). Bug also present in K2 (200122_Unofficial_Opus)
With a frequency of about 10-20%, when I start interface it fails to load most or all of my scripts, including default scripts, it has been verified by several others, including some poor souls trying hifi for the first time.
I did send log files at the time And I can do that again on request but I don’t really see anything in there that looks related.
This came about at the same time as the unwarranted stolen avatar messages and I’m pretty sure they are related, I don't really use marketplace avatars anymore but I would assume that this is also still happening.
There is a non-zero chance this may go away when we change metaverse API but at-least now it's on-record.

To reproduce: well, It happens a lot to me but some never see it? I usually load in my local sandbox but I don't think it makes a difference, maybe metaverse server ping related?

**Comment by Basinsky** [comment]
I can confirm I have the same issue. If you dont have the developer mode on you even cannot push the load defaults button. Loading defaults generally fixes everything. But if you cannot find that, interface is unusable. I also think it has something to do with the unwarranted avatars.

**Comment by ctrlaltdavid** [comment]
PR: https://github.com/kasenvr/project-athena/pull/162
