### ISSUE TITLE
Desktop Mode Camera don't follow avatar orientation

### ISSUE THREAD

**Issue by AleziaKurdis** [kasenvr/project-athena#125]
Running a script that changes the gravity orientation of an avatar, the camera was following the orientation of the avatar in HMD and in Desktop, But somewhere during the last 6 months of Hifi this stopped to work for all the different camera mode in desktop. (Not, it still works in VR)

Found in Release: **0.86 (Hifi)**
Type: **BUG**
Priority: **Medium**
Size: **S**

**Comment by daleglass** [comment]
Odysseus: this relates to the tiny world script

**Comment by odysseus654** [comment]
http://metaverse.bashora.com/planetoid.php

**Comment by AleziaKurdis** [comment]
The solution is to use the legacy "third person" camera mode.
(This one make this possible for non HDM view)

        if (!AvatarInputs.isHMD) {
            Camera.mode = "third person";
        } 

I'm closing this bug.
