### ISSUE TITLE
Create: Properties page, reorganize the UI without scrollbars

### ISSUE THREAD

**Issue by AleziaKurdis** [kasenvr/project-athena#126]
When we are using the “Properties“ page of the “Create” tool, scrolling is a big pain, in VR is very clunky to use, in Desktop it tends to do weird focus lost too. In addition to this, it's a pain to find the section we need and it's even more a pain when we have to do back and forth. 

To solve this problem, maybe we can consider to get rid of the scrollbar and replace this by a tab system. Each section would be a tab with a recognizable icon. This way in a click we get immediately where we want to be, without having to fight with a very painful scrolling every single time (in HMD mainly, but in desktop it's not too much better.). 

Remember Second Life, the small building tool was built like this. Without being the most perfect thing in the world, it was however very easy to use. Far better than searching by scrolling.

Found in release: **0.86 (Hifi)**
Type: **Enhancement**
Priority: **Medium**
Size: **L**

Ex:
![image](https://user-images.githubusercontent.com/60075796/73124658-bccfb180-3f6b-11ea-8473-3162dee597f4.png)

**Comment by AleziaKurdis** [comment]
Coded:
See: PR 193
https://github.com/kasenvr/project-athena/pull/193#issue-382088999

To be closed once released.

**Comment by kasenvr** [comment]
https://github.com/kasenvr/project-athena/pull/193 This was completed by @AleziaKurdis, thank you! :)
