### ISSUE TITLE
Add a “Duplicate” button on the Entity list of the “Create” application

### ISSUE THREAD

**Issue by AleziaKurdis** [kasenvr/project-athena#127]
In “VR” it's impossible to duplicate an entity. This is problematic. A simple “Duplicate” button on the entity list would be helpful. 
Maybe add a warning message (OK/Cancel) when using this button. If it gets hit accidentally it could be not evident to figure in a huge list of entities.

Found in release: **0.86 (Hifi)**
Type: **Enhancement**
Priority: **Low**
Size: **S**

**Comment by JulianGro** [comment]
This can be closed since https://github.com/kasenvr/project-athena/pull/760 is merged, right?
