### ISSUE TITLE
Interface crashes when opening create tools

### ISSUE THREAD

**Issue by Akira-Kuru** [kasenvr/project-athena#131]
When opening the createtools the interface crashes. This doesn't always happen but has been happening recently in the palace. Possibly it has to do with the number of assets in the asset list?

**Comment by daleglass** [comment]
Are you running the Athena version? Which commit are you on?

Also, what operating system are you using?

What do you see in the logs?


Also, for future reference, this might (or not) have something to do with this, not in that the commit breaks it, but that it shows that there's some kind of problem in there:
https://github.com/kasenvr/project-athena/pull/39

**Comment by Akira-Kuru** [comment]
Version would be:  Project Athena v0.86.0 K2 - Version K2_200122_unofficial_Opus
Operation System: Windows 10 Pro

[hifi-log_2020-01-25_22.48.58.txt](https://github.com/kasenvr/project-athena/files/4112922/hifi-log_2020-01-25_22.48.58.txt)

**Comment by daleglass** [comment]
Hmm, unfortunately there's nothing of help in the log, and this is on Windows.

I'll try and see if a Windows dev can help here.

**Comment by ctrlaltdavid** [comment]
@Akira-Kuru  Next time Interface crashes when you open the Create app in ThePalace, maybe post a message in Discord case a dev is available to repro and debug? It could be because of a problematic entity present at the time.

**Comment by Akira-Kuru** [comment]
@ctrlaltdavid & @daleglass so after the backup of the ThePalace. I noticed that the creation tools now work. Possibly it was because the domain was lagging that it was crashing on my side. Since i can not recreate it anymore. I would close this issue.
