### ISSUE TITLE
Crash reporting for Interface

### ISSUE THREAD

**Issue by kasenvr** [kasenvr/project-athena#132]
We can probably integrate the area to submit the report into the launcher, however we need to find out how to access the backtrace from the crash and put that next to the logs so it can also be submitted.

**Comment by HifiExperiments** [comment]
currently traces get sent to a service called backtrace.io, I wonder if we can get an account with them?  I don’t know what it costs, if anything.  they’ve got some great dashboards and debugging tools

**Comment by daleglass** [comment]
The pricing is at: https://backtrace.io/product/platforms-2/

TL;DR:

Free for single devs.
$99/month for games with up to 1000 active monthly users, plus $0.008 for each user over 1000.
Custom plan otherwise.

**Comment by kasenvr** [comment]
We're currently looking into Sentry.io (self hosted) as a potential solution to this.

**Comment by ctrlaltdavid** [comment]
Separate user setting for submitting crash reports: https://github.com/kasenvr/project-athena/pull/257

**Comment by kasenvr** [comment]
Crash reporting has effectively been enabled and setup in the Interface, a back-end was also deployed by way of Sentry. Interface's crash reports have optimized variables for processing through Sentry.
