### ISSUE TITLE
Apidocs no longer easily mobile usable

### ISSUE THREAD

**Issue by vegaslon** [kasenvr/project-athena#138]
Apidocs used to be readable on mobile device. Now with new theme they are almost completely unusable.

**Comment by kasenvr** [comment]
https://apidocs.highfidelity.com/Clipboard.html

I load this on my mobile and it does not look mobile friendly. How can I recreate the mode you are thinking of?

**Comment by vegaslon** [comment]
Ideally it would be better to function like the docs page with a menu for sidebar but barring that, sidebar should scale down more on mobile devices and allow scrolling left to right on main text.

**Comment by kasenvr** [comment]
I agree, it's just that I wanted to make sure functionality was not broken. Mobile mode on the API Docs would be a feature mode. Would be cool though, I can look into it.

**Comment by ctrlaltdavid** [comment]
From what I can see, the API docs weren't ever mobile friendly but the user docs were (and still are): If you narrow the browser window displaying the user docs, with narrow views the display switches such that the sidebar disappears and is replaced by a three-horizontal-bars gizmo that shows the sidebar instead of page content. (Tested with final High Fidelity version of API docs.)

**Comment by vegaslon** [comment]
The original api docs did not have a scaling sidebar, that made them viewable on mobile devices using zooming in and out, the new version does and so always ends up taking away half the screen when you use zooming.

**Comment by kasenvr** [comment]
https://cdn.discordapp.com/attachments/654475781581439029/672289849914425404/Screenshot_20200129-225644.png

I'm using Brave Browser on Android. I saw the problem you have but got around it easily by checking "Desktop Site" in the browser settings. Have you tried that? Which mobile browser are you using?

**Comment by vegaslon** [comment]
chrome browser on iOS and Requesting the desktop version does not make a difference. https://photos.app.goo.gl/um7vEhQJDi8YSFnx5 verses https://photos.app.goo.gl/w6NdeRZipqc1WHb18

is a very big difference in usablity,

**Comment by kasenvr** [comment]
https://apidocs.projectathena.dev/staging/out/ Try this.

**Comment by vegaslon** [comment]
it looks good, the sidebar button could go a little bigger it is hard to click on a cellphone.

**Comment by kasenvr** [comment]
Made the button slightly bigger.

https://github.com/kasenvr/project-athena/pull/140
