### ISSUE TITLE
Create a Linux appimage or flatpack build

### ISSUE THREAD

**Issue by paju1986** [kasenvr/project-athena#142]
It would be great if you create an appimage or flatpack linux build of the interface, so it can be easilly installed on any linux distribution-

**Comment by kasenvr** [comment]
What Linux distro do you have? We have a .deb prototype going, usually Ubuntu is extremely popular for server owners.

**Comment by paju1986** [comment]
I'm on archlinux, I have the knowlage to build from source as i did with hifi before but it's a pain in the butt

**Comment by daleglass** [comment]
I've got a build script if that works for you: https://github.com/daleglass/athena-builder

But I've done some work on appimage in the past and am going to try to give it another look after I'm done with my vacation, if nobody else does it sooner.

**Comment by kasenvr** [comment]
Oh, I was being a dummy, didn't notice you mentioned interface. We've got things going server wise, but a package for interface is being looked at as Dale said.

**Comment by kasenvr** [comment]
This is something that is being actively prototyped and can be downloaded here for testing purposes: https://vircadia.com/download-vircadia/

**Comment by daleglass** [comment]
Added to vircadia-builder
