### ISSUE TITLE
Make URLs in new chat app be able to copied and pasted

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/project-athena#154]

**Comment by Akira-Kuru** [comment]
You should be able to copy URLs by right-clicking them and clicking "copy link address". 
[https://i.gyazo.com/b257882024a637a6ce49bdafb096be57.png](example)
In this example, the address would come out as `javascript:gotoURL('https://bit.ly/386WOdM');`
Maybe the javascript:gotoUrl can be removed.

**Comment by ctrlaltdavid** [comment]
Note: Right-click and using "copy link address" gives you (' ') around the URL, which need to be removed.
