### ISSUE TITLE
"Game Controller" toggle absent from Athena RC1 client

### ISSUE THREAD

**Issue by Aitolda** [kasenvr/project-athena#161]
In the original 0.86.0 the option to use "game controller" is found in the controller settings directly between "user real-world height (meters):" and "Perception Neuron"  (scroll down).

In Athena RC1 this is completely absent.  Therefore Windows controllers like the Xbox One controller no longer function.

original
![0 86 0](https://user-images.githubusercontent.com/21160271/74001291-eac7d500-491f-11ea-9bc4-8873bfd56b99.png)

Athean RC1
![RC1](https://user-images.githubusercontent.com/21160271/74001337-1054de80-4920-11ea-8c60-adcec499d77a.png)

**Comment by daleglass** [comment]
Looking in the code, the game controller is implemented in plugins/hifiSdl2

This sounds like the Windows build is missing the SDL2 dependency.

**Comment by daleglass** [comment]
Just addressed this in the Linux build script

**Comment by daleglass** [comment]
Re-tested, it's present now, so it seems to have been fixed.
