### ISSUE TITLE
Feature: allow negative light intensity values in create menu

### ISSUE THREAD

**Issue by SilverfishVR** [kasenvr/project-athena#197]
already supported by the engine, but the create menu discards it, you can do some cool stuff with negative light.

**Comment by AleziaKurdis** [comment]
I will work on this.

Is it only for the "Light" entity?
Is "Zone" Keylight Intensity support that too?

**Comment by ctrlaltdavid** [comment]
Note: Should probably update the API docs' JSDoc to say that values can be negative (and perhaps give range off valid values).

**Comment by AleziaKurdis** [comment]
Changes for the editor are part of PR #215 

For the JSDoc, this is on the c++ side. (I don't compile so I'm hesitant to do any change there that I can't test)

The range in the editor are those ones: 

- ZONE: **keyLight.intensity** (-40 to 40)
- ZONE: **ambientLight.ambientIntensity** (-200 to 200)
- LIGHT: **intensity** (-1000 to 1000)

But I'm not sure what is the real range accepted by the entity, I simply reported in the negative the existing value already set for the positive.

**Comment by kasenvr** [comment]
This was completed and merged in https://github.com/kasenvr/project-athena/pull/193, thank you!
