### ISSUE TITLE
Add chat notification sound

### ISSUE THREAD

**Issue by kasenvr** [kasenvr/project-athena#201]
When interface is not focused, have a sound (that you can toggle) play when a new chat message arrives. Have a delay of 3-10s before allowing the sound to be played again?

**Comment by Aitolda** [comment]
I think a delay is appropriate, not sure how many seconds, maybe 2-3?  I also think its important that we be able to toggle this off as some people will likely want the option.

**Comment by Aitolda** [comment]
Maybe just an overall toggle for sound on all text channels,  which would also be informed by the individual mute of each channel.

For example,  If you use the existing "mute" option on the local channel, this would also mute the audio notification for said channel, however, if you hit the "mute audio notifications" toggle, it would do so on all channels (Local, Domain, Grid).

**Comment by Aitolda** [comment]
I propose using
[This sound](https://aitolda.s3.amazonaws.com/sounds/bubblepop.wav) at a fraction of the volume for chat popups  (maybe 0.1)

**Comment by Aitolda** [comment]
More thoughts on the sound mute for it. I recommend a speaker icon toggle that adds a red "NO" symbol or slash when muted.
