### ISSUE TITLE
Suggestion:  Disable "Create Entities as Grabbable" by default.

### ISSUE THREAD

**Issue by Aitolda** [kasenvr/project-athena#209]
This is an option in the edit menu that is checked ON by default.  I can't tell you how many times I've started to work on an elaborate build only to find out nearly all objects are grabbale after someone visits in VR and accidentally redecorates.

**Comment by kasenvr** [comment]
The Create tools should have a settings tab to have toggles like this so we can select a preference I reckon. The reason High Fidelity originally did this was likely to make worlds more interactive and accessible to VR builders right off the bat, but yeah... it does disrupt a lot when you don't want it.

**Comment by odysseus654** [comment]
FWIW I ended up resetting the teleport doors in the Hub tonight.  It appears that entity that parents the whole structure was set (accidentally) as grabbable.

**Comment by kasenvr** [comment]
Many menu items were added because they were supposed to be moved to a proper area for settings later, this would be the perfect example of such an item that people seldom know of and can wreak havoc.
