### ISSUE TITLE
ToS needs updating before K2 release

### ISSUE THREAD

**Issue by kasenvr** [kasenvr/project-athena#216]
Can anyone look into a generic Terms of Service template, preferably for open source software and services related? (We will be hosting a metaverse API, etc.) We want to do this before K2 releases, but the RC2 is fine for now.

We probably want to release K2 on the weekend of the 28th of March, 2020. :)

**Comment by ctrlaltdavid** [comment]
This refers to the ToS displayed in the installer. The current (High Fidelity) ToS used in the installer is in the file, "LICENSE" in the repo root.

**Comment by ctrlaltdavid** [comment]
PR: https://github.com/kasenvr/project-athena/pull/219
