### ISSUE TITLE
Login screen at start-up should emphasize the "no thanks" and de-emphasize the "log in"

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/project-athena#229]
The current login at start-up screen is confusing for new users.

**Comment by Aitolda** [comment]
I agree that it's confusing.  Even when Vircadia has an account system, I would like to see something like a simple either/or selector.
-Log in with account
-Log in anonymously

If "Log in with account " is selected the name and password boxes are visible
If "Log in anonymously" is selected the name and account boxes are hidden.

No need to hide anonymous option at the far corner. Keep is front and center along with the account option.
