### ISSUE TITLE
Explore App: Add a Name to the Location Marker box

### ISSUE THREAD

**Issue by AleziaKurdis** [kasenvr/project-athena#233]
When the Explore app generate the Location marker (box entity)
It would be helpful to generate the entity with a name, something like "LOCATION MARKER: {place Name}". Since that object is going to be invisible, without a name it can be a bit painful to find it in a long list of entities.
The box should also be generated collisionless and not grabbable.

**Comment by kasenvr** [comment]
Good idea, I'll open a PR to make those changes.
