### ISSUE TITLE
Interface crash in domain using Athena server

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/project-athena#235]
At least one user crashes in domains running Athena server using the Opus coded.
- Windows K2 RC2  Interface.
- User tried different microphones as well as changing sample rate.
- User doesn't crash if removes (or renames?) the Opus DLL.
- User doesn't crash if Opus is disabled on the domain.
- User doesn't crash with HiFi Interface.

- [ ] New crash dump needed for debugging. See AppData\Local\CrashDumps. Verify K2 RC being used that is crashing.
- [ ] Copy of program log directory may also be useful.
- [ ] More testing needed with more users in Opus-powered domains. (E.g., community meeting at TheHub.)

**Comment by ctrlaltdavid** [comment]
User no longer crashing in TheHub but still crashing in BearCave.
Crash dumps and program logs not received yet.

**Comment by kasenvr** [comment]
Is this an ongoing issue? The Hub is hosted with the Opus Codec, and people do crash... but we are unsure as to why. I believe more information can be ascertained once crash reporting is online for all clients.

**Comment by daleglass** [comment]
Only Windows? Are there any Linux ones?

**Comment by kasenvr** [comment]
Does this still happen since #429 was merged?

**Comment by daleglass** [comment]
I think #429 was the most likely culprit

**Comment by daleglass** [comment]
Seems to be already fixed, please reopen if it still happens
