### ISSUE TITLE
Login dialog can display "High Fidelitiy" instead of "Project Athena"

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/project-athena#244]
Reported by Aitolda in K2 RC2.1, a user encountered this. I haven't managed to repro. However, there are some issues in the code:
- Project Athena SVG used in the login dialog(s): \interface\resources\images\project-athena-banner-color2.svg
- Original, High Fidelity SVG used in login dialog(s) still exists: \interface\resources\images\high-fidelity-banner.svg
- The Project Athena SVG is used in some places.
- The High Fidelity SVG is used in OverlayLoginDialog.qml

**Comment by JulianGro** [comment]
This should be fixed, as there have been a couple of PRs that remove HighFidelity branding: #356 #384 #437
