### ISSUE TITLE
Redirect starter serverless domain teleport

### ISSUE THREAD

**Issue by kasenvr** [kasenvr/project-athena#258]
It needs to be directed to "hub.vircadia.com" instead of "welcome" which is now defunct.

**Comment by Aitolda** [comment]
This existing serverless tutorial doesn't have a teleporter...

Is it possible you meant the sandbox?

**Comment by kasenvr** [comment]
Maybe, the sandbox does need good starter content. And the inventory app with pre-filled CC0 assets will help greatly with that.

With regards to a teleporter, maybe for now then at least some sign to point to opening the Explore app to find places to go to?

**Comment by JulianGro** [comment]
How is this confirmed?
Aitolda invalidated this report. I just checked and there really is not teleporter in the serverless.

**Comment by kasenvr** [comment]
Mayhaps the confirmed is in reference to adding indication towards the Explore app? That will be done on the new Onboarding Sandbox anyway so we'll close this now.
