### ISSUE TITLE
Seemingly random jitter

### ISSUE THREAD

**Issue by JulianGro** [kasenvr/project-athena#259]
When in VR on the Valve Index I get seemingly random jitter. It is like I see a couple of frame from a different perspective. I guess I should try to take a video of it, as it is pretty hard to describe.

**Comment by odysseus654** [comment]
This sounds like something I've had occasionally with the Oculus Rift S, where I'd occasionally get a flash from a completely different perspective

**Comment by SilverfishVR** [comment]
I started getting this issue last Saturday for no apparent reason, sometimes a little, sometimes alot and nothing seemed to help.

Today before starting the interface I rid my _interface.json_ of any _"Avatar/avatarEntityData/..."_ lines as well as the _""Avatar/avatarEntityData/size": ..."_ line, I believe this is also known as barnacle removal :grimacing:

Anyway, I did not see the issue so it could be related, or just coincidence but maybe you could try it @jug007 to confirm or disprove?

**Comment by jug007** [comment]
This issue didn't happen to me when briefly trying out the openvr-update branch. So either it was fixed by that, or it is some other issue.
I am always pretty lazy when it comes to testing VR stuff on windows, so I might not come around to do any more testing.

**Comment by JulianGro** [comment]
Closing this, as I haven't encountered the issue in a while.
