### ISSUE TITLE
Spacial audio does not always work

### ISSUE THREAD

**Issue by JulianGro** [kasenvr/project-athena#261]
I can often hear people as if they were inside of my, even though they are far away. The volume also *seems* to sometimes ignore the distance.

**Comment by Aitolda** [comment]
For reference, which headset are you experiencing this on?

**Comment by jug007** [comment]
This is in desktop mode. I don't specifically remember if I had the problem in VR as well.

**Comment by JulianGro** [comment]
Closing, as I didn't have this issue in a long time.
