### ISSUE TITLE
Camera app shows up in shots!

### ISSUE THREAD

**Issue by drfranny** [kasenvr/project-athena#288]
Any time I take a photo or gif, the camera widget shows up in the shot.

![hifi-snap-by-DrFran-on-2020-04-07_18-15-50](https://user-images.githubusercontent.com/13889300/79028334-96c6b000-7b5d-11ea-9ab4-479811c25b9c.gif)
![hifi-snap-by-DrFran-on-2020-04-10_18-50-23](https://user-images.githubusercontent.com/13889300/79028314-831b4980-7b5d-11ea-8a5e-fd86f7e52068.gif)

**Comment by languagelovr** [comment]
I can confirm this has also happened to me 2-3 times and typically restarting the interface (temporarily) fixes it.

**Comment by JulianGro** [comment]
Not sure how to reproduce this. It happens sometimes to me, but rarely.
