### ISSUE TITLE
Renderer ignores vertex colors if only one value is given.

### ISSUE THREAD

**Issue by Aitolda** [kasenvr/project-athena#294]
If a mesh is imported with only one vertex color on all vertices, it will appear in interface as white or uncolored. However, use at least two distinct values and the color appears as expected.

Note: This was only tested importing from blender 2.82 stable, and may need someone with maya or other 3d software to see if this is consistent.

**Comment by daleglass** [comment]
Please link or attach a model that reproduces the issue

**Comment by Aitolda** [comment]
Update:  Only FBX models seem to be affected by this bug.

[fbx](https://aitolda.s3.amazonaws.com/test/vertexbug/vertexcolors.fbx)
[glb](https://aitolda.s3.amazonaws.com/test/vertexbug/vertexcolors.glb)
