### ISSUE TITLE
GLTF/GLB inverted backface lighting.

### ISSUE THREAD

**Issue by Aitolda** [kasenvr/project-athena#297]
GLTF files will let you show backfaces, however, both shadow and specularity at the least seem to be showing up incorrectly, or appear flipped on these backfaces.
![LightInversionBackface](https://user-images.githubusercontent.com/21160271/79411718-6f565580-7f58-11ea-96c7-c60d1f449956.png)
Image attached.

You can see the underside of the leaves reflecting the sky and shadow from above showing through.

**Comment by SilverfishVR** [comment]
![backfaceNormals 2020-04-16 23 14 51](https://user-images.githubusercontent.com/53531160/79507555-38577100-8038-11ea-88ab-a3323bfb28fd.png)

Same for materials with _"cullFaceMode": "CULL_NONE"_
Left is the backface, right is the front, the backface clearly has the same worldspace normal as the front so it will be lit wrong, I don't know engines usually handle this.

**Comment by Aitolda** [comment]
This is corrected in [PR301](https://github.com/kasenvr/project-athena/pull/301)
