### ISSUE TITLE
"Auto" Developer/Rendering/Maximum Texture Memory just sets it to 1 GB.

### ISSUE THREAD

**Issue by daleglass** [kasenvr/project-athena#30]
The setting is not "auto" whatsoever and just sets it to a hardcoded value of 1GB. This is incredibly wasteful on modern hardware, with cards having memory amounts of 8GB quite often.

I already looked into it, and intend to try to submit a fix soon-ish. Submitting the bug here for tracking purposes.

**Comment by kasenvr** [comment]
After looking into this, I think it might be a good idea to remove the auto option entirely and put this setting as part of the graphics settings so the user can handle this. Let the "auto" type function be instead having the max texture memory scale with the presets.

Users are used to having to fine-tune graphics settings for all matters of games and 3D apps so they can definitely set the custom amount if need be. If anything, a notice can be given that the amount of memory the world wants is higher than their settings is allowing perhaps?

To make an almost sort of black box algorithm to have it dynamically scale, especially where there are few official/reliable cross-platform ways to ascertain enough information about available, total, used video memory seems quite a bit of an undertaking at this time, too early on.

Though, the app initially setting the max memory to be perhaps 70% of the maximum available to the system (suggested by Dale) would be a good idea where it's possible to ascertain the necessary parameters.
