### ISSUE TITLE
blurry textures when loading new avatar

### ISSUE THREAD

**Issue by JulianGro** [kasenvr/project-athena#307]
When loading in a new avatar, the textures of that avatar are often blurry.
Reloading content fixes this.
For example, this happens with this: http://motofckr9k.ddns.net/m/Effole9.fbx
It doesn't happen every time.
Maybe #14 is related?

**Comment by kasenvr** [comment]
Have you tried raising the Maximum Texture Memory? Go to Developer -> Render -> Maximum Texture Memory. Would be good to narrow down the source of it.

**Comment by jug007** [comment]
Yeah, I the tests I did now, it did actually help to set the Maximum Texture Memory.
Rather than setting it to automatic, setting it to 4 gigabyte made the issue disappear and not happen again.

**Comment by kasenvr** [comment]
Yes, so there are a LOT of settings in the menu that are not where they should be. This was added preliminarily as High Fidelity added support for things but didn't really get them into the main software experience, so we're going to want to make these sorts of things more accessible and in the actual user interface.

**Comment by JulianGro** [comment]
I think I might understand now why this happens.
When the texture resolution is limited by the texture memory, we likely fill up the memory as much as possible.
So when a new/additional texture comes in, there is no space for it to go to. I would assume that at this point, rather than resizing all textures, it just resizes the new texture to fit into the tiny space that is left.

A way to work around this might be to reserve something like 10% of the texture memory for future textures. Since we should always run into this problem if texture size is limited by texture memory. We will almost always have someone join afterwards and an additional texture be loaded.

**Comment by JulianGro** [comment]
#599 is a good enough fix
