### ISSUE TITLE
option to catch mouse

### ISSUE THREAD

**Issue by JulianGro** [kasenvr/project-athena#321]
When using desktop mode, it can feel really limiting to only be able to move the camera when holding down right click.
An option to catch the mouse would be pretty cool for this.
Maybe add a shortcut for catching and uncatching the mouse and add an info for that onto the screen until you hide it.
Or potentially just add an option for mouse catching in the settings and have the tablet available when pressing the escape key or something similar.
I would personally even argue that the mouse should be caught by standard, but that is open for discussion.

**Comment by SilverfishVR** [comment]
Currently when in VR, the desktop window catches the pointer if you mouse over it and it is quite annoying and generally useless, I would like to see that change.
In VR I often have to peek out to do something on the desktop and it bugs me that if I accidentally mousing over the interface window you cursor goes Puff!
