### ISSUE TITLE
Update to latest OpenVR SDK

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/project-athena#330]
- [ ] Update driver.
- [ ] Test / fix current functionality on the HMDs & controllers currently supported.
    - [ ] Oculus Rift + SteamVR with Touch controllers
    - [ ] Vive with Vive controllers
    - [ ] WMR with WMR  controllers

Downstream tasks:
- Updates to support other HMDs and controllers.
- Update to improve controllers support.
- Update to support Linux.

**Comment by jug007** [comment]
#239

**Comment by ctrlaltdavid** [comment]
PR: https://github.com/kasenvr/project-athena/pull/335
