### ISSUE TITLE
Steam authentication support 

### ISSUE THREAD

**Issue by JulianGro** [kasenvr/project-athena#331]
We talked about how there should be an easy way for the not so tech savy user to authentificate themselves. I feel like, since most of the users will be using Steam, the easiest way for all those users would be to use their Steam identity. Thry would not need to login, or do anything really. It could just do this in the background when starting Vircadia via Steam. 
I am assuming that we want to put Vircadia on Steam eventually anyways, but even if not, most users with VR-headsets will use SteamVR and probably 99% of those users will use Steam.

**Comment by AleziaKurdis** [comment]
Using only one specific corporation as an authentication system would go in contradiction with the philosophy behind the Vircadia project. (And I doubt seriously that 99% are using steam systematically, many oculus user don't.)

We can keep this open to use any authentication source (Which could include Steam) But not only it. Personally, I wouldn't want to have anything to do with any corporation, Steam or even worse Oculus (owned by Facebook).

**Comment by kasenvr** [comment]
I think specifically this would help as a module for the Metaverse API. However, I'm not sure how strict Valve is to letting someone be a vendor for using their authentication so I don't know if it's a module that everyone would use.

**Comment by jug007** [comment]
Yeah. I was mostly thinking about the time "when Vircadia gets on Steam", but looking at the rules for that, that might not nessesarily even be an option.
They do have rules about age gating, and they do not actually say anything about free software on their site.
On the other hand there is adult games, as well as free games on Steam.

**Comment by JulianGro** [comment]
Closing as this fits better into Project Apollo and is a very future issue.
