### ISSUE TITLE
Linux PR builds broken `distro` not found

### ISSUE THREAD

**Issue by thoys** [kasenvr/project-athena#347]
The PR builds for linux are broken with the error

```
ModuleNotFoundError: No module named 'distro'
```

Note:

```
pip3 install distro || exit 1
```
is executed successfully see `Successfully installed distro-1.5.0`

**Comment by thoys** [comment]
The builds that worked used `-- Found Python3: /usr/bin/python3.6 (found version "3.6.9") found components: Interpreter `   while the failing build seem to find `Found Python3: /home/linuxbrew/.linuxbrew/bin/python3.7 (found version "3.7.7") found components: Interpreter ` in CMake

**Comment by daleglass** [comment]
Okay, so sounds like it's finding the wrong Python then. I can think of two possible fixes:

1. Install the module in the other one:  `/home/linuxbrew/.linuxbrew/bin/pip3 install distro`
2. Remove the brew python from `$PATH`.

**Comment by thoys** [comment]
Or allow specifying a python path in CMake. Which seems to make sense in
this situation of a machine with many python installs

**Comment by daleglass** [comment]
I think in this situation, removing it from the path is going to be easier. There's other things like Qt that also look for Python, so an option may require patching other things as well.
