### ISSUE TITLE
Vircadia Launcher not aware of Limited Accounts in windows

### ISSUE THREAD

**Issue by 1st-BrainStormer** [kasenvr/project-athena#370]
I tried Vircadia Quantum, when to running scripts, Tried loading a new script.
But only my local drives are listed and none of my mapped drives. went back to
K2, it shows the drives. So something changed.

**Comment by 1st-BrainStormer** [comment]
Seems the installer doesn't understand Administrative and Limited accounts on windows.
On my system All accounts are Limited to they require a password to install (Like linux and su)
The installer only set up the administrative account and not the local account.

**Comment by 1st-BrainStormer** [comment]
In the Limited User Account I only see AppData\Local\vircadialauncher-updater and nothing in AppData/Roaming.

**Comment by thoys** [comment]
Is that the same issue? Your second issue seems related to the installer.

**Comment by 1st-BrainStormer** [comment]
I believe so. The new Launcher isn't compatible with Limited Accounts.

**Comment by 1st-BrainStormer** [comment]
So it should install into both Admin and the Limited User accounts AppData folders and use relative paths so each user has there own folders.    Right now it asks for the Admin password when you run it.  it should only ask if an update is to be installed.

**Comment by 1st-BrainStormer** [comment]
It would be best if Vircadia Launcher was installed in:  C:\Program Files\Vircadia Launcher
and the default install folder should be C:\Program Files\Vircadia Launcher\storage
This would allow ALL USERS on the machine to be able to run the launcher and Vircadia from the launcher since they would be in folders they have permissions to read and execute.

Right now the Vircadia Laucher download page says you need administrator privileges to run.  This isn't entirely correct.  You have to be THE administrator that installed installed it.  So other administrators and limited users can't run it as it is right now.

**Comment by kasenvr** [comment]
As of the current build of the launcher, this issue is solved by allowing the launcher to be run not as an administrator, install to program files by default, and warn if you are not an admin when performing an elevation required action. :)

**Comment by 1st-BrainStormer** [comment]
https://github.com/electron-userland/electron-builder/issues/3824
