### ISSUE TITLE
K3Q: Delete entities don't work from a Serverless domain.

### ISSUE THREAD

**Issue by AleziaKurdis** [kasenvr/project-athena#378]
K3Q
(This is a regression)

in a serverless domain 
(you can go there: http://metaverse.bashora.com/explore/limbo.php)
Create 2 or 3 zones entities
Select them, click on the Delete button  (in the create app: entity list)
They are removed from the list, but they are still present in-world.
If you refresh the list using the radius search, they re-appears in the list.
(The same thing work correctly on a domain or using K2 in both serverless and domain)

All type of entities are affected.

**Comment by SilverfishVR** [comment]
Same issue in PR369 sandbox (K3), "reload content brings back deleted items, thugh I have sucessfully deleted a lot of items, so sometimes it sticks.
