### ISSUE TITLE
Zones are resized to the size of a cube when spawned

### ISSUE THREAD

**Issue by kasenvr** [kasenvr/project-athena#380]
I noticed that the zone starts off larger than me and flashes into the smaller size before happening, perhaps this was not intended functionality by High Fidelity?

**Comment by AleziaKurdis** [comment]
Shapes are now larger too (same size as zone). In previous release, the default size was like 0.25 m

**Comment by kasenvr** [comment]
https://github.com/kasenvr/project-athena/commit/2fc0f01928bf94bf1bd3dfafbd7b1b84c4d68ae9

Reverting this commit corrects the problem. There is something in this commit that is causing this behavior.
