### ISSUE TITLE
K3Q: Some Models are badly misaligned and resized.

### ISSUE THREAD

**Issue by AleziaKurdis** [kasenvr/project-athena#383]
REGRESSION
Some Models are badly misaligned and resized.

Under K2, add this model to a domain:
**http://metaverse.bashora.com/objects/RANTAR/DEADTOWN.baked.fbx**

Then using K3Q go see that model. The "origin" get moved to the "position" but "position" seems to still be considered as a reference somewhere else in the code, causing a bad and distorted scaling.

**Comment by kasenvr** [comment]
![image](https://user-images.githubusercontent.com/52365539/83340598-24926200-a2a8-11ea-8db2-75224ed23beb.png)
With similar camera positions, it's clear something odd is going on here. (same domain, same location.)
![image](https://user-images.githubusercontent.com/52365539/83340603-3247e780-a2a8-11ea-95f8-f8597c9e0ba8.png)

**Comment by ctrlaltdavid** [comment]
Probably broke in commit 3592488, HiFi build 11184
"Instancing: Introduce hfm::Shape to enable Instancing support"

**Comment by AleziaKurdis** [comment]
OBSERVATIONS:
1-
We can exclude the "Baking" from the equation:
(Here, viewed in K3Q, the non-baked versus the baked version of a model affected by the problem, both are squeezed indentically)
![unknown](https://user-images.githubusercontent.com/60075796/83477103-6fef7080-a460-11ea-9e97-d8a594e80ea1.png)

2-
The Origin point, for **recent** FBX seems to not be in problem.
(this cube has the origin offset and it doesn't get deformed. This is an FBX exported from Blender 2.8  using the Menithal plugin. http://metaverse.bashora.com/objects/TESTS/cubeTest.fbx)
![CUBE_ORIGINE_OFFSET_K2](https://user-images.githubusercontent.com/60075796/83477333-0885f080-a461-11ea-8df3-91c0baef384e.png)
![CUBE_ORIGINE_OFFSET_K3Q](https://user-images.githubusercontent.com/60075796/83477344-0c197780-a461-11ea-9d8f-f495c10a5af2.png)

3-
This one is just making the problem more confusing:
![PILLAR CASE_K2](https://user-images.githubusercontent.com/60075796/83477472-4d118c00-a461-11ea-8ede-3c75de8fd32f.png)
![PILLAR CASE_K3Q](https://user-images.githubusercontent.com/60075796/83477924-7e3e8c00-a462-11ea-95a3-fbf20d9874d9.png)
This is an fbx exported by the blender plugin under Blender 2.79.
http://metaverse.bashora.com/objects/WOTHAL/PILAR.fbx
I have no explanation about how it can shrink like this.
you can see the container the same. But it gets rescale on 2 axis, which is not fitting the hypothesis of the Origin point offset.
But it does have the origin offset (as the other broken one)
![image](https://user-images.githubusercontent.com/60075796/83477890-623aea80-a462-11ea-8dc9-d8cb56d29800.png)

So far, the only conclusion we can have is that they have all been created under Blender Pre-2.8
with the blender exporter.

**Comment by kasenvr** [comment]
2 broken example:
http://metaverse.bashora.com/objects/RANTAR/DEADTOWN.baked.fbx
http://metaverse.bashora.com/objects/RANTAR/DEADTOWN.fbx

http://metaverse.bashora.com/objects/RANTAR/KHOS-HOUSE.baked.fbx
http://metaverse.bashora.com/objects/RANTAR/KHOS-HOUSE.fbx

Not broken
http://metaverse.bashora.com/objects/RANTAR/KHOS-TERRASSE.baked.fbx
http://metaverse.bashora.com/objects/RANTAR/KHOS-TERRASSE.fbx

**Comment by Aitolda** [comment]
Not sure I have any answers yet, but after doing some testing with the Pillar above, it appears to import visually at the right size in scale, however in the create tools it's showing as exactly twice it's scale on the x and z axis within interface, while the Y axis (up/down) is acurate to scaled size in blender (which is the Z axis within blender).  HOWEVER... in blender this axis is actually the ONLY part that is scaled.  So...   the non-scaled axis are showing up with incorrect dimensions, while the scaled dimension shows up incorrectly.

In Blender note the scaling and length on the Z axis (Y within interface)
[Blender](https://i.gyazo.com/50ce43c18fb4232f6406af977f761a50.png
)

And note the Y-dimensions within the create menu in interface (again)
https://i.gyazo.com/e58fd49e0bda9b00b9d735a163da0035.png

Both remain at 17.8, but the other two dimensions are doubled in interface.  Again, they actually are showing up at the correct visual scale for me, just not in the create dimensions.
