### ISSUE TITLE
Zones with scripts don't get enterEntity calls on first try

### ISSUE THREAD

**Issue by AleziaKurdis** [kasenvr/project-athena#398]
I have a Client Entity Script that creates a zone and then fails to update the "keyLight.direction" properties using Entities.editEntity. 
The result is that the zone looks like completely as inheriting the higher zone over it, despite that the Create app display the expected values

To reproduce:
In a Test domain or in the Serverless domain, import this json:
**http://metaverse.bashora.com/scripts/hytrion/galax_Edit.json**
This create a zone that run a script _(http://metaverse.bashora.com/scripts/hytrion/galactic_sky_edit.js)_ that generates a sub zone and update it's "keyLight.direction" each 3 seconds.
But that sub zone (named "DEEPSPACE") appears completely black. (as the zone over it)

I discovered after a couple of hour of test, that "Entities.editEntity", to update correctly a zone's attribute, needs that we force an update of the Mode attributes ("keyLightMode", "ambientLightMode", "skyboxMode",  "hazeMode" and "bloomMode") **with at least one** attribute of that mode.
Without this, the display ignores the update and behave as if the mode was set to "inherited".

I was expecting to be able to update only one specific attribute using the Entities.editEntity and have the existing context to be assumed as it is.
To me, this is clearly a bug.

Also to workarround the issue, I had to include this in my update:
                "keyLightMode": "enabled",
                "ambientLightMode": "enabled",
                "skyboxMode": "enabled",
                "hazeMode": "enabled",
                "bloomMode": "enabled",  
in addition of at least one attributes under each of these Mode, even if I didn't need that.

It's clearly not intuitive.

**Comment by AleziaKurdis** [comment]
Seems to be related to events like enterEntities that are not triggered when a script is attached to an entities. Apparently for the session where this script runs for the first time.
The impact might affect lot of things. This script will never work well when a visitor come the first time in a domain. The owner might conclude it working when he visit a second time. (until a cache refresh) 
Not sure this is low severity.

**Comment by HifiExperiments** [comment]
I looked into this and I think you're right that the issue is related to enterEntity, not the zone properties specifically.  I can create a zone and edit its keyLight direction from the console without changing the other properties.

I think what's happening is that scripts take time to download.  For most entity types, if they have an attached script, we wait until the script loads to call enterEntity on them.  However, for zones, we usually want them to appear right away, regardless of if they have scripts (see EntityTreeRenderer::findBestZoneAndMaybeContainingEntities: `if (isZone || scriptHasLoaded)`)

I see two possible solutions:
1. Change it so that zones with scripts attached don't appear until their scripts are loaded (this is an easy fix, but might be undesirable)
2. Keep it so that zones with scripts appear right away, but figure out another way for them to call enterEntity properly (a little more complicated, perhaps, and also a little confusing that enterEntity could be called a bit after the zone appears)

I would rename this issue something like "Zones with scripts don't get enterEntity calls on first try"

**Comment by AleziaKurdis** [comment]
Issue renamed.

When I re-think about it, I realize that I have observed the same issues with another script that play a local sound for a wind ambiance on at least 2 of my domain. It behaves exactly like this. (It was just more easy to forget a sound than a sky)
But that script is in a "shape" entity. (A very large one, where we also land directly inside of it)
So I think this is not limited to "Zone" entity. It's just running too late to catch "enter Entity".
The script I this one: http://metaverse.bashora.com/scripts/ambientSoundWothalEnter.js
And this script is in place since October 2018. With this issue.

Solution 1.
I would avoid that one.

Solution 2
The questions, here, is probably those ones:
Can we consider an avatar present inside the volume as "entering the entity" when a script start ?
Is there a usecase where we don't want to be considered as "entering the entity" if we are inside the volume when a script start?
It might be very hazardous to go that way.

Solution 3
Document the Limitation of EnterEntity when we are already in the place when the script run?

Let's see if there is another way to script that?
What if I check if the avatar is inside the volume at the "preload" ?
If I'm not wrong the sequence would be
1- The user position is known
2- The entity get loaded
3- the script of the entity preload
(Enter entity won't happened since your entering is already done)
If at preload I'm not in, then enter entity would work. (so I have to check for the 2 events)

When I will come in the domain for a second time, is preload will happen again ?

So maybe it's addressable by script, clearly not simple for beginner to figure this.
but if the limitation is documented correctly, it might be ok.

I will have to test that.

**Comment by thoys** [comment]
Yes, you can use preload for this. Preload will happen every time that the entity will be loaded. See https://github.com/highfidelity/hifi-content/blob/ca50df0779e905ce8059441722e30fb2f7d32ee7/usefulUtilities/unmuteZone/unmuteZoneClient.js#L58 for an example. It has a function to check if the avatar is inside of the entity on preload.      Changing the behavior of enterEntity in the system would have as side-effect that scripts that were using this work-around technique will trigger the enterEntity functionality twice.

**Comment by AleziaKurdis** [comment]
Exactly.
However, I think that would merit to be mentioned in the documentation of enterEntitity.
(People would need that info to avoid a server back and forth in their scripting. You have no idea how much I had to do and undo my script to figure what was happening)

I checked the script unmuteZoneClient.js, it's fine when the entity is rectangular not rotated. (it would do the job for me)
That might become another level of complexity if it's rotated or if the shape is not rectangular.

Do you know:
for "Shapes", is enterEntity care about the shape it-self or just the overall rectangular volume?
For a “Model”… what is considered as being inside the entity?

Maybe that would worth to have a method for getting info like: **isInsideEntity(EntityId, position);** 
The computation is not very simple even for a basic cube when this one is rotated. It’s a bit heavy to have to script that every time we need it.

**Comment by AleziaKurdis** [comment]
This solved my case.


For the doc:  https://apidocs.vircadia.dev/Entities.html#.enterEntity
I suggest to replace:

**Triggered when an avatar enters an entity, but only if the entity has an entity method exposed for this event.**

by:

**Triggered when an avatar enters an entity, but only if the entity has an entity method exposed for this event. Note: At the loading of the entity, if the avatar is already present inside the entity, it might be too late to catch this event when the script runs, so it won't trigger. The 'preload' signal can be used to handle those cases.**

Please, if someone could rephrase this for me in a decent English, I would consider making a PR to update the doc.

**Comment by HifiExperiments** [comment]
Regarding checking if you are inside an entity: there is currently no way to check if you are inside a specific entity as far as I know (that’s a great feature request), but Entities.findEntities returns a list of all entities you are inside, and does real containment checks (not just axis-aligned bounding boxes).  In other words, for a model, it actually checks if you are inside the model.

I think your suggestion to update the docs is great.  But just to clarify, when you mention leaving the domain and coming back, is the problematic entity recreated every time?  Or does the issue happen every time an entity is created around you?

If so, I would maybe say: *Triggered when an avatar enters an entity, but only if the entity has an entity method exposed for this event. Note: This method is _not_ called when an entity is created around you, only when you move or teleport inside one. The 'preload' signal can be used to handle those cases.*

**Comment by AleziaKurdis** [comment]
_I think your suggestion to update the docs is great. But just to clarify, when you mention leaving the domain and coming back, is the problematic entity recreated every time? Or does the issue happen every time an entity is created around you?_

Basically, it's **persistent Zone entity** geared with a script, and this script generate a sub Zone (a local entity) and updates this zone local entity based on the avatar position.  So for a specific visitor, the sky is different depending on where he is in that local zone entity.
![image](https://user-images.githubusercontent.com/60075796/83933879-7a6c7b80-a77a-11ea-836f-d4b6827b38b7.png)
I think the enterEntity event gets missed because, the at 1st visit, the script have to be downloaded. (which take some time). But at the second visit, the script is already in the cache and this makes probably the difference.
But there is still one things that I couldn't explain.
It happened that the sub zone didn't displayed, but the update cycle was started (apparently the enterEntity was worked at some point), weirdly, EditEntity wasn't failed since it was returning the id (and not a null). Like if the entity was existing. I got the same kind of weird result changing the local for a "domain" entity, and it was visible in the Create App. If I changed a value, it started to display.
I have the feeling that we might have walled a deeper problem.

**Comment by AleziaKurdis** [comment]
I just read you suggestion of text.
It's not accurate, in the present case, I was teleport inside the persistent zone, but the script started too late to catch the event.

**Comment by kasenvr** [comment]
Shall we consider this solved then? :)

**Comment by AleziaKurdis** [comment]
Definitely.
When scripted according the doc, it works A1.
Other solutions would imply a level of complexity that doesn't worth it.
Let close this.
