### ISSUE TITLE
K2: Local Entities make crash interface when teleporting to a serverless domain.

### ISSUE THREAD

**Issue by AleziaKurdis** [kasenvr/project-athena#404]
Local entities, being persistent when we navigate from a domain to another,
makes crashing Interface when we navigate to a Serverless Domain.

To reproduce:
1- On a domain, create a local entity (not parented)
2- Navigate to a **serverless** domain (you can go there: http://metaverse.bashora.com/explore/limbo.php)
Interface crashes.

**Comment by kasenvr** [comment]
Is this effect present on a Quantum or Master build as well?

**Comment by kasenvr** [comment]
I tried this on Quantum with the following command:

```
var entityID = Entities.addEntity({
    type: "Box",
    position: Vec3.sum(MyAvatar.position, Vec3.multiplyQbyV(MyAvatar.orientation, { x: 0, y: 0, z: -5 })),
    rotation: MyAvatar.orientation,
    dimensions: { x: 0.5, y: 0.5, z: 0.5 },
    lifetime: 300  // Delete after 5 minutes.
}, "local");
```
Then navigated to the domain "limbo.php" as instructed and did not crash. 

This may very well be fixed in master, I will close this for now. If anyone finds this to be an issue in a master build, please open a new issue. :)
