### ISSUE TITLE
K3 (Quantum) fbx models with multiple objects display incorrect positions.

### ISSUE THREAD

**Issue by Aitolda** [kasenvr/project-athena#412]
If an fbx has multiple unconnected models, some of those models will be offset when the fbx is brought into K3/Quantum.  This is not the case in K2

[Comparison](https://i.gyazo.com/0705cdf9d61122e4193da6c5c35d2907.jpg)

Model on the left (ignore colors) has the "cog" and logo in the background shifted from their proper position.  Model on the right is when the objects were combined as one before importing, therefore they show up in the correct positions. Again, ignore color differences.

**Comment by kasenvr** [comment]
Related to https://github.com/kasenvr/project-athena/issues/383 ?

**Comment by ctrlaltdavid** [comment]
PR414 fixes the problem with that model. (Displays OK in L2, broken in Quantum, OK in PR414 build.)
