### ISSUE TITLE
Debug build crash at start-up: "vector subscript out of range"

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/project-athena#42]
/kasen/core  Commit: 8c86b5fb98c27b429eb25523160dce7118220548 [8c86b5f]
VS2017

Call stack:
>	interface.exe!std::vector<AnimPose,std::allocator<AnimPose> >::operator[](const unsigned __int64 _Pos) Line 1733	C++
 	interface.exe!AnimBlendDirectional::evaluate(const AnimVariantMap & animVars, const AnimContext & context, float dt, AnimVariantMap & triggersOut) Line 99	C++
 	interface.exe!AnimBlendLinear::evaluateAndBlendChildren(const AnimVariantMap & animVars, const AnimContext & context, AnimVariantMap & triggersOut, float alpha, unsigned __int64 prevPoseIndex, unsigned __int64 nextPoseIndex, float dt) Line 91	C++
 	interface.exe!AnimBlendLinear::evaluate(const AnimVariantMap & animVars, const AnimContext & context, float dt, AnimVariantMap & triggersOut) Line 48	C++
 	interface.exe!AnimOverlay::evaluate(const AnimVariantMap & animVars, const AnimContext & context, float dt, AnimVariantMap & triggersOut) Line 56	C++
 	interface.exe!AnimOverlay::evaluate(const AnimVariantMap & animVars, const AnimContext & context, float dt, AnimVariantMap & triggersOut) Line 56	C++
 	interface.exe!AnimOverlay::evaluate(const AnimVariantMap & animVars, const AnimContext & context, float dt, AnimVariantMap & triggersOut) Line 56	C++
 	interface.exe!AnimOverlay::evaluate(const AnimVariantMap & animVars, const AnimContext & context, float dt, AnimVariantMap & triggersOut) Line 56	C++
 	interface.exe!AnimTwoBoneIK::evaluate(const AnimVariantMap & animVars, const AnimContext & context, float dt, AnimVariantMap & triggersOut) Line 55	C++
 	interface.exe!AnimPoleVectorConstraint::evaluate(const AnimVariantMap & animVars, const AnimContext & context, float dt, AnimVariantMap & triggersOut) Line 45	C++
 	interface.exe!AnimTwoBoneIK::evaluate(const AnimVariantMap & animVars, const AnimContext & context, float dt, AnimVariantMap & triggersOut) Line 55	C++
 	interface.exe!AnimPoleVectorConstraint::evaluate(const AnimVariantMap & animVars, const AnimContext & context, float dt, AnimVariantMap & triggersOut) Line 45	C++
 	interface.exe!AnimStateMachine::evaluate(const AnimVariantMap & animVars, const AnimContext & context, float dt, AnimVariantMap & triggersOut) Line 93	C++
 	interface.exe!Rig::updateAnimations(float deltaTime, const glm::mat<4,4,float,0> & rootTransform, const glm::mat<4,4,float,0> & rigToWorldTransform) Line 1628	C++
 	interface.exe!Model::updateRig(float deltaTime, glm::mat<4,4,float,0> parentTransform) Line 1397	C++
 	interface.exe!MySkeletonModel::updateRig(float deltaTime, glm::mat<4,4,float,0> parentTransform) Line 337	C++
 	interface.exe!Model::simulate(float deltaTime, bool fullUpdate) Line 1390	C++
 	interface.exe!SkeletonModel::simulate(float deltaTime, bool fullUpdate) Line 164	C++
 	interface.exe!MyAvatar::simulate(float deltaTime, bool inView) Line 925	C++
 	interface.exe!MyAvatar::update(float deltaTime) Line 773	C++
 	interface.exe!AvatarManager::updateMyAvatar(float deltaTime) Line 168	C++
 	interface.exe!Application::update(float deltaTime) Line 6557	C++
 	interface.exe!Application::idle() Line 5257	C++
 	interface.exe!Application::event(QEvent * event) Line 4214	C++
 	[External Code]	
 	interface.exe!Application::notify(QObject * object, QEvent * event) Line 4171	C++
 	[External Code]	
 	interface.exe!main(int argc, const char * * argv) Line 442	C++
 	[External Code]	

![Debug Assert](https://user-images.githubusercontent.com/7455448/71528115-45ded300-2943-11ea-8d3e-0599e596b333.png)

**Comment by daleglass** [comment]
seems to be closed in master
