### ISSUE TITLE
When starting interface in VR Mode High Fidelity branding is still visible at login.

### ISSUE THREAD

**Issue by HeadClot** [kasenvr/project-athena#436]
Pretty self explanatory from the title. Image below to show what I am seeing.

Version: Latest from the website.

![image](https://user-images.githubusercontent.com/1534098/84103082-505fc700-a9cf-11ea-8105-e361ad5cd890.png)

**Comment by HeadClot** [comment]
The PR that @kasenvr made fixed it :)

**Comment by kasenvr** [comment]
This was fixed in PR #437 Thank you!
