### ISSUE TITLE
Avatar Packager - Users aren't aware their avatar is ready when they reach the "Upload" button.

### ISSUE THREAD

**Issue by Aitolda** [kasenvr/project-athena#46]
We are going to need to make a slight modification to the avatar packager.  As far as I know, all the processes of packaging and checking for errors is fine and happens locally.  At the point the packager finally says "Upload," users have no way of knowning their avatar has actually been prepared and a sent to "C:\Users\youraccount\Documents\High Fidelity Projects." The upload button currently takes this avatar and moves it to the High Fidelity marketplace.  This button will have to be removed.

My suggestion for the time being is a simple fix.  Remove the upload but and leave a message indicating where they can find their packaged avatar (locally), followed by a link to a document explaining some of their options (digital ocean, amazon, etc).  It would really be nice to see this in K2, as I suspect it's a quick fix.

**Comment by ctrlaltdavid** [comment]
I'm having a look at this.

**Comment by zontreck** [comment]
Without a marketplace (which is where it uploads to), the upload button will become broken anyhow. Should this be replaced with a "open folder" button? Or if you have a FTP location set, perhaps have it upload there? (new feature?)

**Comment by Aitolda** [comment]
"Should this be replaced with a "open folder" button?"

This is probably ideal for the time being.  Might also be good to leave a note saying something like "Please upload these contents to a public folder in the cloud" or something like this.  (I'm sure it could be described better).

**Comment by ctrlaltdavid** [comment]
PR: https://github.com/kasenvr/project-athena/pull/58

**Comment by ctrlaltdavid** [comment]
PR has been merged.
