### ISSUE TITLE
Explore: No clear indication of when a Location is successfully added.

### ISSUE THREAD

**Issue by Aitolda** [kasenvr/project-athena#477]
When using the Expore app to drop a location (teleportaiton point), there is no indication that you've succeeded.  The menu remains on the same page, and there is no sound or anything.  This results in years dropping multiple landing points on top of each other, without realizing, and multiple entries in the Explore app.

Suggestion
1. after successfully placing, shift to a new page indicating so.
2. play a sound effect.

**Comment by kasenvr** [comment]
This will be solved with the Explore app redesign.

**Comment by kasenvr** [comment]
The menu now closes on complete, though later we can add more indication. Re-open if this still turns out to be a problem for people.
