### ISSUE TITLE
Should the Vive's "use devices in desktop mode" setting be sticky?

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/project-athena#483]
Currently, in the Vive's Settings > Calibration dialog, the "Use OpenVR devices in desktop mode" always starts up as false; a true value isn't remembered between program runs.

**Comment by kasenvr** [comment]
It would be relatively easy to do a Settings.getValue / Settings.setValue though for that, wouldn't it?

**Comment by ctrlaltdavid** [comment]
Fixed (made sticky) as part of fixes included in https://github.com/kasenvr/project-athena/pull/484
