### ISSUE TITLE
Linux Mint 19.3 building stopped working with v2020.2.2

### ISSUE THREAD

**Issue by JulianGro** [kasenvr/project-athena#490]
Trying to build current master on Linux Mint 19.3 (Ubuntu 18.04) results in
```
RCC: Error in '/home/motofckr9k/Vircadia/build/interface/resources.qrc': Cannot find file '/home/motofckr9k/Vircadia/source/tools/jsdoc/out/hifiJSDoc.json'
```
Build log: https://gist.github.com/JulianGro/1ca12aef8c36f4bf288eccb1f042bd0b

**Comment by JulianGro** [comment]
Here is vircadia builder run with `--collect-info` [vircadia-builder-error-2020-05-29_T08_47_49.tar.gz](https://github.com/kasenvr/project-athena/files/4844230/vircadia-builder-error-2020-05-29_T08_47_49.tar.gz)

**Comment by JulianGro** [comment]
Little update on what we found out so far:
- building k2 generates the jsdoc/out folder successfully
- building master does not generate the jsdoc/out folder and failes because of that
- master builds successfully if jsdoc/out is already present

**Comment by JulianGro** [comment]
This seems to be an issue with my specific system only.
Linux Mint 19.3 with and without updates is able to build master successfully in my virtual machine. Interestingly it does not generate anything into the jsdoc/out directory.
So the issue seems to be that the build process wants `jsdoc/out/hifiJSDoc.json` on my system, but not when testing on my virtual machines.

**Comment by ctrlaltdavid** [comment]
What cmake command do you use to configure the build?
Is the same cmake command used on both your VM and development PC?
What versions of node - `node --version` - are on your VM and development PC?
What versions of npm - `npm --version` - are on your VM and development PC?

**Comment by JulianGro** [comment]
I don't actually know what cmake command I use. It should be the same on both though, as that is done by the same vircadia-builder.
node is version v8.10.0
npm is where it gets interesting. It is not installed on the VM, but version 6.14.5 is installed in my main system. I also don't know where that comes from, as it apparently does not come from the package manager.

So I will try to find out where I got npm from and what happens when I remove it. Also I might dig into the cmake command a bit.

**Comment by JulianGro** [comment]
We just found the issue!
Since npm was clearly orphaned, I deleted it and restarted the machine.
Master builds without issue now.

I will do some more testing to see if the builds generally fail if npm is installed, but I will open a new issue for that if that happens.

**Comment by ctrlaltdavid** [comment]
With npm not installed the JSDoc will not be attempted to be built - which is probalby why your VM was succeeding.

To build JSDoc you need both Node (`node --version` to check) and npm. The build scripts only check for npm though. So perhaps Node wasn't installed or not installed properly - which would mean that the JSDoc build step would fail and so cause that "cannot find file" error. ... If Node was installed then I expect that the JSDoc building step was failing for some other reason.

There are instructions in \tools\jsdoc\README.md to manually build the JSDoc if at any time you want to try building it.
