### ISSUE TITLE
Vertex colors on gltf look different from FBX and "entity color"

### ISSUE THREAD

**Issue by SilverfishVR** [kasenvr/project-athena#496]
something about how gamma correction is handled is off so dark colors appear darker on gltf.

As I understand it, colors values entered in blender are gamma corrected, but converted to linear on export (for gltf), models imported as fbx will be the same color as an entity with its color property set to the same value, so I assume the values in Vircadia are also gamma corrected.

this: https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/VertexColorTest/VertexColorTestCubes.json is nine cubes of each type (glb, fbx, and shape entities) in RGB shades of _0xff 0x99_ and _0x33_
![Screenshot 2020-06-30 20 34 05](https://user-images.githubusercontent.com/53531160/86164948-e12f4b80-bb12-11ea-8fdd-701a2fe200f4.png)

**Comment by HifiExperiments** [comment]
dupe of https://github.com/kasenvr/project-athena/issues/302

**Comment by SilverfishVR** [comment]
ups, sorry, forgot about that. closing because duplicate
