### ISSUE TITLE
Feature Request.  Explore Address bar should behave more like a browser, including a search feature.

### ISSUE THREAD

**Issue by ArtworkJustBecause** [kasenvr/project-athena#525]
I find myself instinctually entering search words instead of exact domain names, which currently have no effect.  Ideally it would reference the current list of places and filter this down based on what you type.  Also, I've subconciously grown to expect some sort of autofill while filling in the box.

**Comment by kasenvr** [comment]
This has been addressed in the latest explore app redesign. Typing in the main search bar now triggers searching. The next step might be to include auto complete using the tab or right arrow key?
