### ISSUE TITLE
Create App: Default particle texture still points to high fidelity hosted texture.

### ISSUE THREAD

**Issue by 1st-BrainStormer** [kasenvr/project-athena#534]
The default texture still points to:
https://content.highfidelity.com/DomainContent/production/Particles/wispy-smoke.png
this should be moved to a Vircadia hosted server or be built into the install so that its stored locally since its a default.

**Comment by kasenvr** [comment]
Hmm.... #535

**Comment by kasenvr** [comment]
Would be ideal to make this and any other references that don't need to be on a CDN be added to the local install perhaps. The tradeoff for space on the initial installer vs reliability for important assets goes in favor of reliability for things this small but so integral I'd think.

**Comment by AleziaKurdis** [comment]
I can take this one since I will have to work on that area for other issues.
