### ISSUE TITLE
Replace all docs.highfidelity.com URLs with docs.projectathena.dev

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/project-athena#61]
Note: Should code the URL in just one place. (And use for the URLs in the Avatar Packager, too.)

**Comment by kasenvr** [comment]
I feel like we got that. https://github.com/kasenvr/project-athena/pull/58 If there's any stragglers, we can make a new issue or handle it on the spot

**Comment by ctrlaltdavid** [comment]
Searchibg the codebase shows there's a bunch of URLs to update: primarily JSDoc but also some QML.

**Comment by ctrlaltdavid** [comment]
PR: https://github.com/kasenvr/project-athena/pull/116

Note: Keep this issue open and re-check for docs.hightfidelity.com URLs once have merged up to master.

**Comment by kasenvr** [comment]
This appears to be completely accomplished for the main codebase. Great job everyone!
