### ISSUE TITLE
Server console still downloads default Sandbox content from HiFi

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/project-athena#611]
/server-console/src/main.js

```
const HOME_CONTENT_URL = "http://cdn.highfidelity.com/content-sets/home-tutorial-RC40.tar.gz";
```

While we're at it, let's remove all the content except for the builder's grid - the content is no longer fully functional.

**Comment by daleglass** [comment]
I can rehost this, or put up a community made archive

**Comment by daleglass** [comment]
Add to the content PR

**Comment by ctrlaltdavid** [comment]
Sandbox content with just builders grid and skybox, from Silverfish: https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/ContentSets/Basic_sandbox_no_external_links.zip
