### ISSUE TITLE
Feature Request: Emit Local "Only" option for particle effects

### ISSUE THREAD

**Issue by Aitolda** [kasenvr/project-athena#616]
Why on earth why we want this?  Well, allow me to paint a picture.  You want to make a world where it's snowing all the time, but you want it to be performant.  With a local only emitter (that is no one else will see said particles at all) you arrive arrive in your winter wonderland.  A particle emitter is scriptted to Automatically attache itself to you and follow you around, giving the illusion that it's snowing throughout the world, but in fact you are the source.  If any others join they will see their own emitter but not yours.

Right now the way to fake this would be to attach a small zone to your avatar's head, add the particle effect as before, but set it to render only in that zone.  It would MOSTLY work, but I suspect since zone effects are depending on the location of the head, if you were to play an animation that brought said head OUT of that zone, you would lose the effect, though I suppose you could try and use scripting to attach the zone to the actual bone.  It might work but it's less than ideal.

**Comment by Aitolda** [comment]
Hmm.   Thinking about this more this isn't helpful in the way I imagined.

**Comment by vegaslon** [comment]
Already works this way can Rez a particle emitter as local only.
