### ISSUE TITLE
Some High Fidelity icons are still present

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/project-athena#617]
If you do a search for *.ico in the project-athena repo there are several High Fidelity icons.
Furthermore, the folders that they're in contain other images also containing the High Fidelity icon.

One of these is perhaps the Mac folder icon which currently shows the High Fidelity logo.
![image](https://user-images.githubusercontent.com/7455448/90100428-c9451b80-dd90-11ea-9c41-c65fa891bf95.png)

Also, search for and check *.icns files (OSX file type).

**Comment by JulianGro** [comment]
I actually had tried to replace the MacOS icons in the past, but they use a proprietary format that I have not been able to find a tool for. I assume you need a Mac to edit those files.

**Comment by JulianGro** [comment]
Influenced by #653

**Comment by kasenvr** [comment]
This was fixed with PR653.
