### ISSUE TITLE
Developer menu still has "Marketplace Item Tester"

### ISSUE THREAD

**Issue by JulianGro** [kasenvr/project-athena#679]
Whatever the "Marketplace Item Tester" does, it will probably at the very least need a rename.

**Comment by kasenvr** [comment]
If this does not cause errors or compile errors: we can simply hide it from the menu for the moment? It may come in handy to verify JSON packages on future implementations.

**Comment by daleglass** [comment]
Is that affected by #666 ?

**Comment by JulianGro** [comment]
> Is that affected by #666 ?

I just checked the repository and the only files I would find have indeed been deleted.
```
motofckr9k@motofckr9k-mint-desktop:~/git/project-athena$ grep -r "Marketplace Item Tester" *
interface/resources/qml/hifi/commerce/marketplaceItemTester/MarketplaceItemTester.qml:            text: "Marketplace Item Tester"
interface/resources/qml/hifi/commerce/marketplaceItemTester/MarketplaceItemTester.qml:            text: "Use Marketplace Item Tester to test out your items before submitting them to the Marketplace." +
scripts/system/commerce/wallet.js:var MARKETPLACE_ITEM_TESTER_LABEL = "Marketplace Item Tester";
motofckr9k@motofckr9k-mint-desktop:~/git/project-athena$ 
```
These two files seem to have been deleted in #666

**Comment by odysseus654** [comment]
Yah I kinda deleted every folder named "wallet" or "commerce" with that patch

**Comment by JulianGro** [comment]
No idea which PR did it, but this was removed
