### ISSUE TITLE
Chat should open Web content in built-in browser rather than its own dialog

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/project-athena#686]
Loading chat in the built-in browser provides the back / forward / reload etc. control bar.

**Comment by JulianGro** [comment]
I am not much of a scripter, but looking at the api, it doesn't seem like you can actually do this.
The OverlayWebWindow class doesn't seem to be able to add those buttons, and the openWebBrowser "Namespace" doesn't take any arguments according to the api docs. (it definitely doesn't work as a drop-in replacement)
