### ISSUE TITLE
Create App: Entity list doesn't update immediately

### ISSUE THREAD

**Issue by JulianGro** [kasenvr/project-athena#696]
When making a change to a property, that change is not shown in the Entity list until something else gets updated.
When selecting an entity, then switching to another entity and then focusing the entities window, the old entity get shown as selected in the entity list again (even though the new one is still selected). This again updates when you change another property.

**Comment by AleziaKurdis** [comment]
I do not reproduce. Can you capture this on video ?

**Comment by JulianGro** [comment]
@AleziaKurdis https://data.moto9000.moe/%23696/create_9_september.mkv

**Comment by AleziaKurdis** [comment]
OK, for what I have seen in the code 
it seems that only imageUrl would be buggy (it works for model & material, but not the Image)
It's missing in a condition that set for a refresh of the list.

I will fix this.
Is someone can assign me this bug?

**Comment by JulianGro** [comment]
One thing you can see in that video as well is that "back refresh" or whatever you might call it. Me clicking a new item on the entitiy list and it jumping to the old one as soon as I focus the properties window and jump to the right one again after changing a property.

**Comment by AleziaKurdis** [comment]
Fixed. ImageURL was missing in a condition that triggers the refresh of the list.

**Comment by JulianGro** [comment]
Created a separate issue for the entity list jumping back to the former entry: https://github.com/kasenvr/project-athena/issues/704
