### ISSUE TITLE
Enhancement: Make create translate "widget" unlit.

### ISSUE THREAD

**Issue by Aitolda** [kasenvr/project-athena#709]
Currently the create widget is is dependant on zone lighting, so if you are working in a low light zone, the widge is hard to see.  This is undesirable.

**Comment by AleziaKurdis** [comment]
entitySelectionTool.js still used 3D Overlays, which are deprecated. We should first convert that to Local Entities.
(We definitely not investing on deprecated things)
Once done, we can consider plugging material entities to this to have them "unlit".

I can at least do the conversion to Local Entities in a first time. It's due.
and then see what we can do to make this "unlit".

**Comment by Aitolda** [comment]
> entitySelectionTool.js still used 3D Overlays, which are deprecated. We should first convert that to Local Entities.
> (We definitely not investing on deprecated things)
> Once done, we can consider plugging material entities to this to have them "unlit".
> 
> I can at least do the conversion to Local Entities in a first time. It's due.
> and then see what we can do to make this "unlit".

I've made an issue for this now
[#721](https://github.com/kasenvr/project-athena/issues/721)

**Comment by AleziaKurdis** [comment]
It seems that we can't apply a material to a Gizmo ring.
So it might be impossible to have the rotation tool unlit.

I wish we could have a "unlit" properties on Shape and Gizmo directly
This would be way more simple. We have it on Image and text already
 To build UI tool, this would make sense.

**Comment by Aitolda** [comment]
> It seems that we can't apply a material to a Gizmo ring.
> So it might be impossible to have the rotation tool unlit.
> 
> I wish we could have a "unlit" properties on Shape and Gizmo directly
> This would be way more simple. We have it on Image and text already
> To build UI tool, this would make sense.

Not sure what the approach was, but they were able to do it in Tivoli early on.

**Comment by ctrlaltdavid** [comment]
I used an `Image` entity for rotation handles and made them unlit by setting their property, `emissive: true`.
Here's a suitable SVG that you can use:
[rotation-circle.zip](https://github.com/kasenvr/project-athena/files/5253236/rotation-circle.zip)

**Comment by AleziaKurdis** [comment]
It wouldn't work for the graduated wireframe ring and the angle circular interval.

**Comment by AleziaKurdis** [comment]
I added Materials. The widget is now "unlit", except for the rotation rings. (It will need the support of Material or unlit on Gizmo ring) But the code is there, ready for it.

I made different attempts, including a shader .fs script to enforce the unlit on the ring. It's not supporting even that.

Using an image or a model entity could have patched the thing, but not without sacrifice the angular visual representation and graduation. And frankly, the original usecase to justify the existence of the Gizmo Ring entity was for that specific usage. I think it can wait. It would take extreme conditions to not even have one side of the ring to not be able to work. (At least now you can see the other elements of the tool in all conditions)
(Bug #744 has been open for the Gizmo ring material issue)

**Comment by AleziaKurdis** [comment]
I think we can close this Issue. and rely only on the #744
