### ISSUE TITLE
Convert entitySelectionTool.js to use local entities instead of 3D overlays, which is deprecated.

### ISSUE THREAD

**Issue by Aitolda** [kasenvr/project-athena#721]
3D overlays are deprecated. 

Doing so is necessary before we make other improvements such as [#709](https://github.com/kasenvr/project-athena/issues/709#issuecomment-693764840)

**Comment by AleziaKurdis** [comment]
Please, assign me this issue.

**Comment by AleziaKurdis** [comment]
PR #737 Replacement of 3D Overlays for Local Entities
