### ISSUE TITLE
Doc: Would like a direct link to Entities.EntityProperties from Entities page

### ISSUE THREAD

**Issue by AleziaKurdis** [kasenvr/project-athena#728]
The entities' properties is certainly among the page that people are using the most. 
But to reach the Common properties we have to navigate by the methods.

Maybe we can enhance the doc in that page: https://apidocs.vircadia.dev/Entities.html

Instead of a "Entity Types" section
![image](https://user-images.githubusercontent.com/60075796/93639083-75000d80-f9c6-11ea-8ac7-4ba1e2111c04.png)

Could we have something like:

**Entity Types and Properties**
For a list of the entity types that you can use, see “**Entity Types**”.
You will also find there the list of properties specific to each type.
For a list of the properties that are common to every entity, see “**Entities.EntityProperties**”.

It will be less a pain, and a lot easier for the newbie to find it.

**Comment by kasenvr** [comment]
Can do. It shouldn't be too hard to change. :)
