### ISSUE TITLE
Vive Tracker calibration is not available

### ISSUE THREAD

**Issue by JulianGro** [kasenvr/project-athena#756]
[According to the docs](https://docs.vircadia.dev/explore/get-started/vr-controls.html?highlight=tracker#configure-your-mocap-system), you just select the devices and press "Calibrate and Apply". This button is greyed out for me on Windows with Valve Index and Vive Trackers.
Since this has been reported to work in the past by people like Ryan, I would assume that it might be just a small thing like the Interface only allowing the calibration if it sees "HTC Vive" as the HMD.

**Comment by Phil-Palmer** [comment]
Hi, I just tested the tracker calibration with HTC Vive and 2 foot trackers, on 2020.3.0_rc.1.  That configuration is working correctly.

**Comment by daleglass** [comment]
Should look into what determines the status of that button in the code

**Comment by daleglass** [comment]
Yes, "HTC Vive" is explicitly referenced here:

https://github.com/kasenvr/project-athena/blob/89c006d190105d9b02661233f3d1910894d1dd25/interface/resources/qml/hifi/tablet/ControllerSettings.qml#L247

and here:

https://github.com/kasenvr/project-athena/blob/89c006d190105d9b02661233f3d1910894d1dd25/interface/resources/qml/hifi/tablet/ControllerSettings.qml#L301

Try poking at that and see if it fixes it?

**Comment by JulianGro** [comment]
Might take me a while to try that. It's a lot of hassle to try and make a build on Windows.

**Comment by JulianGro** [comment]
I tried it on Linux and for some reason, if I change even the just string on those lines, it breaks my QML. Not sure what is up with that.
But whatever I do, I cannot do much more than a workaround anyways. This would have to be solved properly, as most headsets will be able to work with OpenVR. Even an Oculus Rift could run via OpenVR.

**Comment by ctrlaltdavid** [comment]
I don't have the relevant HMDs to test with but looking at the code ...

The button appears to be enabled/disabled in:
https://github.com/kasenvr/project-athena/blob/89c006d190105d9b02661233f3d1910894d1dd25/interface/resources/qml/hifi/tablet/OpenVrConfiguration.qml#L1150

And the settings are calculated in:
https://github.com/kasenvr/project-athena/blob/89c006d190105d9b02661233f3d1910894d1dd25/interface/resources/qml/hifi/tablet/OpenVrConfiguration.qml#L1187

Are the heads, hands, and additional tracker options available in your tracker configuration dialog, per
https://docs.vircadia.dev/explore/get-started/vr-controls.html#motion-capture-using-vive-trackers ?

Perhaps a screen snap of the dialog you see?

**Comment by JulianGro** [comment]
The options are all available like on https://docs.vircadia.dev/_images/vive-config.PNG
Only real difference is the name of the HMD and that the button at the bottom only says "Apply" and is greyed out.

**Comment by ctrlaltdavid** [comment]
What option buttons do you have selected?

**Comment by JulianGro** [comment]
`Valve HMD` for `Head`
`Controllers` for `Hands`
and then `Feet` and `Hip`, but changing the options did not seem to have any impact.

**Comment by Phil-Palmer** [comment]
Hi, if you tick 'Use HTC Vive devices in desktop mode', does the Apply button stay greyed-out?

**Comment by ctrlaltdavid** [comment]
The QML dialog could be crashing on loading, thus preventing its script from running and so not enabling the button.
From log file it looks like this _might_ be happening per the following program log entry:
```
[WARNING] [default] qrc:/qml/hifi/tablet/OpenVrConfiguration.qml:1048: Error: Cannot assign [undefined] to double
```
https://github.com/kasenvr/project-athena/blob/89c006d190105d9b02661233f3d1910894d1dd25/interface/resources/qml/hifi/tablet/OpenVrConfiguration.qml#L1048
I.e., the HMD plugin isn't setting the `armCircumference` property value.

**Comment by JulianGro** [comment]
Yeah something is going terribly wrong here. For some reason my builds don't have QML and it is not disabled in the cmake thingee

**Comment by JulianGro** [comment]
I opened a PR for a hacky fix: https://github.com/kasenvr/project-athena/pull/808
Would be great if someone could fix this properly as almost every HMD can be used with OpenVR and therefor almost every HMD could be used with Vive Trackers.
