### ISSUE TITLE
3.0 Demeter: All machines on the same network/router are considered localhost by domain permissions.

### ISSUE THREAD

**Issue by Aitolda** [kasenvr/project-athena#765]
This is new behavior.  If I give localhost permissions to my machine hosting my sandbox, and then visit the domain from my other machine on the same network/router, despite not being logged in or the same machine, localhost permissions affects this machine.

**Comment by kasenvr** [comment]
I just tried this with my Demeter sandbox on my local server and it still rejected me. I was not able to reproduce your issue on 2020.2.5 or 2020.3.0, so maybe there was another setting in there letting you in other than just localhost? Or it could be an odd network configuration.

The one thing I did not try was with using a place name to connect. So at least we know this is not a regression in the core code.

**Comment by kasenvr** [comment]
Tested with a place name, it still rejected me unless I whitelisted the IP addresses manually.

**Comment by Aitolda** [comment]
This is no longer an issue.
