### ISSUE TITLE
3.0 Demeter: Explore app add location still refers to a place/location as "Domain Display Name."

### ISSUE THREAD

**Issue by Aitolda** [kasenvr/project-athena#766]
You can have as many locations as you want on a single domain, so refering to this as a domain is misleading and confusing.  Location would also be an acceptable description, but if I recall we're wanting to eventually tie location beacons from the explore to metaverse places.

[Screenshot](https://gyazo.com/f5848855c1f9ca26ce2355592ea2f3a9)

**Comment by ctrlaltdavid** [comment]
In the current implementation, I suggest changing it to "Location Name". Other items in the dialog are in terms of "location".
