### ISSUE TITLE
Incorrect "update is available" message in Chat

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/project-athena#779]
In Chat I'm told (in purple), "Interface: An update is available. 2020.3.0". ... But I'm on 2020.3.0.
Aitolda has the same problem.

**Comment by kasenvr** [comment]
I fixed the issue by adding back a line in the meta file that I had removed. I'm not sure I followed semver spec completely but for now, she works, should revisit the checking code in utils.js for proper support of version checking on Release Candidates though.

Please confirm that this does not happen anymore.

**Comment by ctrlaltdavid** [comment]
It no longer happens for me.
