### ISSUE TITLE
"Reload Content" should be made available in general settings

### ISSUE THREAD

**Issue by kasenvr** [kasenvr/project-athena#785]

**Comment by SilverfishVR** [comment]
is "Clear Caches" different from the "Reload Content" found in the  _Edit_ menu and in the _Developer->Network_ menu?

**Comment by kasenvr** [comment]
Nope, I mean the same thing.

**Comment by kasenvr** [comment]
Though one consideration is that this can be a crashy action due to the script engine, depending on what you have running.

**Comment by kasenvr** [comment]
I had misunderstood what Silverfish meant with this, it appears that those are the same so nevermind! :)
