### ISSUE TITLE
Enable flying in VR by default

### ISSUE THREAD

**Issue by Akira-Kuru** [kasenvr/project-athena#82]
When using VR the flying functionality which is used in desktop is disabled by default.

**Comment by Phil-Palmer** [comment]
Hi, I'm investigating this now.  Jump/fly seems to have been moved to the MENU button of the right Vive controller.  Does anyone know why that would be?  Thanks!

**Comment by ctrlaltdavid** [comment]
The PR enables flying in VR by default in new installations of Interface (and if Interface.json is deleted).
The location of the jump/fly button on Vive controllers is a separate issue which I've lodged here: https://github.com/kasenvr/project-athena/issues/395
