### ISSUE TITLE
Qt resources are generated in the source directory, not the build directory

### ISSUE THREAD

**Issue by daleglass** [kasenvr/project-athena#856]
This means that cleaning the build directory doesn't perform an entirely clean build, and this has caused problems in the past

**Comment by kasenvr** [comment]
So the resources.rcc file?

**Comment by daleglass** [comment]
yes

**Comment by kasenvr** [comment]
They want so far as to make a "compiledResources" folder to put it in unless that's by default, so it may not be a trivial fix, dunno. But yes, I agree this is very annoying.

**Comment by kasenvr** [comment]
Also related (duplicates):

https://github.com/kasenvr/project-athena/issues/670
https://github.com/kasenvr/project-athena/issues/570

**Comment by daleglass** [comment]
Duplicated
