### ISSUE TITLE
New Zones appear as parent of a ghost child. Issue with Entities.getChildrenIDs()

### ISSUE THREAD

**Issue by AleziaKurdis** [kasenvr/project-athena#869]
New Zones appear as parent of a ghost child. Issue with Entities.getChildrenIDs()

1- Create a new zone, (note that it is displayed as a Parent, which doesn't make sense.)
2- Select the zone, then do "Selection... > Add Children to Selection" (the selection in the list become display as no more the last entity, the selection in-world is now grey, as for a multiple selection)
3- from the list, keep pressed CTRL, and deselect the zone. Now you see the mysterious ghost child in cyan selected in-world.

![image](https://user-images.githubusercontent.com/60075796/99343508-0a4f3f00-285c-11eb-98de-e6509e956252.png)

This happens only with zones. The ghost disappears if we add another entity that is not a zone.

The thing is that it doesn't seem to be the editor.
As you can see here, this is the piece of script that is responsible to figure what is the parent state of the entity:

function getParentState(id) {
    var state = "NONE";
    var properties = Entities.getEntityProperties(id, ["parentID"]);
    var children = Entities.getChildrenIDs(id);
    if (properties.parentID !== Uuid.NULL) {
        if (children.length > 0) {
            state = "PARENT_CHILDREN";
        } else {
            state = "CHILDREN";
        }
    } else {
        if (children.length > 0) {
            state = "PARENT";
        }
    }
    return state;
}

Entities.getChildrenIDs() seems to return something when it's a new zone entity for any obscure reason.
For sure, that ghost child has an id, since it's able to determine that it has a parent. What's hidden behind this?
Severity: **Medium**
Priority: **Medium**

**Comment by HifiExperiments** [comment]
is it possible that this is something that edit.js is making?  the “zone outline” thing where it shows a grid when you select a zone is accomplished with some local entities + a material entity, maybe they’re not being initialized properly?

**Comment by AleziaKurdis** [comment]
It does make sense. I will check how this has been done.

This leads to some questions...
Is a local entity can be parented to an a domain entity ? (I guess this would be possible)
is a domain entity can be parented to a local entity?  (This might be a bit dirty)

What would be the most performant?
- looping (script side) on the results returned by Entities.getChildrenIDs() to exclude the local entities
- or have this done (code side) with an eventual optional parameter like Entities.getChildrenIDs(onlyDomainEntities)

**Comment by AleziaKurdis** [comment]
I added some code to exclude the non-domain entities
properties = Entities.getEntityProperties(allChildren[i], ["localEntity", "avatarEntity"]);
        if (!properties.localEntity && !properties.avatarEntity) {
            domainOnlyChildren.push(allChildren[i]);
        }
Weirdly, the zone entity is sometimes returning a domain entity child.. like a glitch 
I don't understand why.

**Comment by HifiExperiments** [comment]
the latter would definitely be more performant, but it might not be a huge issue

also, yeah, you can attach a local entity to a domain entity, and the reverse is possible but is probably undefined behavior (I think it’d be normal for you but not other people).  there are similar issues with avatar entities

I also think you could check entityHostType == domain instead of both of those other flags

**Comment by AleziaKurdis** [comment]
properties.entityHostType == "domain"
solved it.

I wonder why... 
localEntity & avatarEntity are set late?
